name: metadata_preservation
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  exif: ^3.2.1
  lottie: ^2.6.0
  image_picker: ^1.0.2
  dotted_border: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/json/